## 1. Write a Python Program to Add Two Matrices?

In [7]:
x = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]  
  
y = [[9,8,7],
    [6,5,4],
    [3,2,1]]

In [32]:
import numpy as np

In [9]:
np.add(x,y)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [33]:
result = [[0,0,0],  
        [0,0,0],  
                [0,0,0]]  
for i in range(len(x)):
    for j in range(len(x[0])):
        result[i][j]=x[i][j]+y[i][j]
        
for r in result:
    print(r)
        

[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


## 2. Write a Python Program to Multiply Two Matrices?

In [13]:
np.multiply(x,y)

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

## 3. Write a Python Program to Transpose a Matrix?

In [16]:
np.transpose(x)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## 4. Write a Python Program to Sort Words in Alphabetic Order?

In [23]:
alpha=['a','c','b','d','r','e','s','x','z','y']
alpha.sort()
alpha

['a', 'b', 'c', 'd', 'e', 'r', 's', 'x', 'y', 'z']

## 5. Write a Python Program to Remove Punctuation From a String?

In [29]:
s="ineuron!"

In [30]:
s.replace('!','')

'ineuron'